### ISSUE TITLE
Studio reports that the .sln file is not a valid solution file

### ISSUE THREAD

**Issue by thuibregtse** [scott-vincent/instrument-data-link#9]
I'm updating software from previous release.   The community edition of Studio reports that the .sln file is not a valid solution file, so I am not able to build.  

Thanks!

**Comment by scott-vincent** [comment]
Make sure you use git to download the files. You can get it from here: https://git-scm.com/
When you have git installed type the following:

git clone https://github.com/scott-vincent/instrument-data-link.git

You will now have a folder called instrument-data-link and the soultion file inside it will be valid. Alternatively, use the solution file from your previous build as it hasn't changed since the original version 12 months ago.

**Comment by thuibregtse** [comment]
The git approach worked.  Thanks!
